KunstmaanArticleBundle_abstractarticlepage_admin_list:
    resource: @KunstmaanArticleBundle/Controller/AbstractArticlePageAdminListController.php
    type:     annotation
    prefix:   /admin/abstractarticlepage/
    requirements:
         _locale: %requiredlocales%

KunstmaanArticleBundle_abstractarticleauthor_admin_list:
    resource: @KunstmaanArticleBundle/Controller/AbstractArticleAuthorAdminListController.php
    type:     annotation
    prefix:   /admin/abstractarticleauthor/
    requirements:
         _locale: %requiredlocales%
